# Generated by Django 5.0.1 on 2024-03-11 10:04

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('motorcycles', '0002_alter_motorcycle_image'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Cart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('delivery_address', models.TextField(blank=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='CartItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(default=1)),
                ('cart', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='moto_cart.cart')),
                ('motorcycle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='motorcycles.motorcycle')),
            ],
        ),
        migrations.AddField(
            model_name='cart',
            name='motorcycles',
            field=models.ManyToManyField(through='moto_cart.CartItem', to='motorcycles.motorcycle'),
        ),
    ]
