# Generated by Django 5.0.1 on 2024-03-11 10:04

import datetime
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('moto_user', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='motouser',
            options={'verbose_name': 'Пользователь', 'verbose_name_plural': 'Пользователи'},
        ),
        migrations.AlterField(
            model_name='motouser',
            name='date_of_birth',
            field=models.DateField(validators=[django.core.validators.MinValueValidator(limit_value=datetime.date(1900, 1, 1), message='Дата рождения не может быть ранее 1900 года.'), django.core.validators.MaxValueValidator(limit_value=datetime.date(2024, 3, 11), message='Дата рождения не может быть в будущем.')]),
        ),
    ]
