# Generated by Django 5.0.1 on 2024-03-20 09:48

import datetime
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('moto_user', '0002_alter_motouser_options_alter_motouser_date_of_birth'),
    ]

    operations = [
        migrations.AlterField(
            model_name='motouser',
            name='date_of_birth',
            field=models.DateField(validators=[django.core.validators.MinValueValidator(limit_value=datetime.date(1900, 1, 1), message='Дата рождения не может быть ранее 1900 года.'), django.core.validators.MaxValueValidator(limit_value=datetime.date(2024, 3, 20), message='Дата рождения не может быть в будущем.')]),
        ),
    ]
